version: 2
updates:
  # Dependabot uses the npm ecosystem for pnpm lockfiles.
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
    ignore:
      - dependency-name: 'node'
        versions:
          - '23.x'
          - '25.x'
          - '27.x'
          - '29.x'
    groups:
      docker:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
    ignore:
      - dependency-name: 'node'
        versions:
          - '23.x'
          - '25.x'
          - '27.x'
          - '29.x'
    groups:
      docker:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /nginx
    schedule:
      interval: weekly
    groups:
      docker:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - '*'
