/**
 * Error Code Constants
 *
 * Mirrors backend error codes from backend/src/common/enums/error-code.enum.ts
 * Used for centralized error handling and translation lookup.
 */

/**
 * All possible error codes from the backend API.
 * These codes are returned in the error.code field of API responses.
 */
export const ErrorCode = {
  // Authentication & Credentials
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',

  // Activation & Registration
  // Wrong code, no pending registration, expired code and locked record all
  // answer ACTIVATION_CODE_INVALID.
  ACTIVATION_CODE_INVALID: 'ACTIVATION_CODE_INVALID',
  NO_PENDING_REGISTRATION: 'NO_PENDING_REGISTRATION',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  // The per-address mailed-code cap is in force; retry after the window.
  EMAIL_SEND_LIMIT_REACHED: 'EMAIL_SEND_LIMIT_REACHED',
  // A registration body still carries a password or a name: the old contract.
  REGISTRATION_CONTRACT_OUTDATED: 'REGISTRATION_CONTRACT_OUTDATED',

  // feature:magic-link:start
  // Magic link
  MAGIC_LINK_INVALID: 'MAGIC_LINK_INVALID',
  // feature:magic-link:end

  // feature:totp:start
  // Two-factor authentication
  TWO_FACTOR_CODE_INVALID: 'TWO_FACTOR_CODE_INVALID',
  TWO_FACTOR_CHALLENGE_INVALID: 'TWO_FACTOR_CHALLENGE_INVALID',
  TWO_FACTOR_ALREADY_ENABLED: 'TWO_FACTOR_ALREADY_ENABLED',
  TWO_FACTOR_NOT_ENABLED: 'TWO_FACTOR_NOT_ENABLED',
  TWO_FACTOR_SETUP_REQUIRED: 'TWO_FACTOR_SETUP_REQUIRED',
  TWO_FACTOR_NOT_CONFIGURED: 'TWO_FACTOR_NOT_CONFIGURED',
  // feature:totp:end

  // feature:passkeys:start
  // Passkeys
  PASSKEY_CHALLENGE_INVALID: 'PASSKEY_CHALLENGE_INVALID',
  // feature:passkeys:end
  PASSKEY_VERIFICATION_FAILED: 'PASSKEY_VERIFICATION_FAILED',
  // feature:passkeys:start
  PASSKEY_NOT_FOUND: 'PASSKEY_NOT_FOUND',
  PASSKEY_LAST_SIGN_IN_METHOD: 'PASSKEY_LAST_SIGN_IN_METHOD',
  PASSKEY_NOT_CONFIGURED: 'PASSKEY_NOT_CONFIGURED',
  // feature:passkeys:end

  // Feature flags
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  NATIVE_AUTH_DISABLED: 'NATIVE_AUTH_DISABLED',
  NATIVE_TRANSACTION_EXPIRED: 'NATIVE_TRANSACTION_EXPIRED',
  NATIVE_DPOP_PROOF_TOO_LARGE: 'NATIVE_DPOP_PROOF_TOO_LARGE',
  NATIVE_DPOP_PROOF_MALFORMED: 'NATIVE_DPOP_PROOF_MALFORMED',
  NATIVE_DPOP_PROOF_DUPLICATE_MEMBER: 'NATIVE_DPOP_PROOF_DUPLICATE_MEMBER',
  NATIVE_DPOP_PROOF_HEADER_INVALID: 'NATIVE_DPOP_PROOF_HEADER_INVALID',
  NATIVE_DPOP_PROOF_ALGORITHM_INVALID: 'NATIVE_DPOP_PROOF_ALGORITHM_INVALID',
  NATIVE_DPOP_PROOF_JWK_INVALID: 'NATIVE_DPOP_PROOF_JWK_INVALID',
  NATIVE_DPOP_PROOF_SIGNATURE_INVALID: 'NATIVE_DPOP_PROOF_SIGNATURE_INVALID',
  NATIVE_DPOP_PROOF_METHOD_MISMATCH: 'NATIVE_DPOP_PROOF_METHOD_MISMATCH',
  NATIVE_DPOP_PROOF_ADDRESS_MISMATCH: 'NATIVE_DPOP_PROOF_ADDRESS_MISMATCH',
  NATIVE_DPOP_PROOF_IAT_INVALID: 'NATIVE_DPOP_PROOF_IAT_INVALID',
  NATIVE_DPOP_PROOF_JTI_INVALID: 'NATIVE_DPOP_PROOF_JTI_INVALID',
  NATIVE_DPOP_NONCE_REQUIRED: 'NATIVE_DPOP_NONCE_REQUIRED',
  NATIVE_DPOP_NONCE_INVALID: 'NATIVE_DPOP_NONCE_INVALID',
  NATIVE_DPOP_PROOF_ATH_INVALID: 'NATIVE_DPOP_PROOF_ATH_INVALID',
  NATIVE_DPOP_PROOF_REPLAYED: 'NATIVE_DPOP_PROOF_REPLAYED',
  NATIVE_DPOP_PROOF_REQUIRED: 'NATIVE_DPOP_PROOF_REQUIRED',
  NATIVE_DPOP_KEY_MISMATCH: 'NATIVE_DPOP_KEY_MISMATCH',
  NATIVE_DPOP_REQUIRED: 'NATIVE_DPOP_REQUIRED',
  NATIVE_DPOP_RETRY_IN_PROGRESS: 'NATIVE_DPOP_RETRY_IN_PROGRESS',
  NATIVE_DPOP_CONFIGURATION_INVALID: 'NATIVE_DPOP_CONFIGURATION_INVALID',

  // Session & Verification
  SESSION_REQUIRED: 'SESSION_REQUIRED',
  SESSION_INVALID: 'SESSION_INVALID',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_LIMIT_REACHED: 'SESSION_LIMIT_REACHED',
  AUTHORITY_UNAVAILABLE: 'AUTHORITY_UNAVAILABLE',
  TRANSACTION_OUTCOME_UNKNOWN: 'TRANSACTION_OUTCOME_UNKNOWN',
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
  APPLICATION_DISABLED: 'APPLICATION_DISABLED',
  GRANT_BLOCKED: 'GRANT_BLOCKED',
  CSRF_REQUIRED: 'CSRF_REQUIRED',
  CSRF_INVALID: 'CSRF_INVALID',
  ORIGIN_REJECTED: 'ORIGIN_REJECTED',
  MIXED_CREDENTIALS: 'MIXED_CREDENTIALS',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',

  // Validation & Input
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Generic Errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  // Client side only: a response with no code and a status with no mapping.
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',

  // User Management
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CANNOT_MODIFY_SELF: 'CANNOT_MODIFY_SELF',
  CANNOT_MODIFY_HIGHER_ROLE: 'CANNOT_MODIFY_HIGHER_ROLE',
  INVALID_ROLE_ASSIGNMENT: 'INVALID_ROLE_ASSIGNMENT',
  USER_ALREADY_DELETED: 'USER_ALREADY_DELETED',
  EMAIL_CHANGE_NOT_ALLOWED: 'EMAIL_CHANGE_NOT_ALLOWED',

  // feature:oauth-core:start
  // OAuth (provider independent: the backend registry names the provider)
  OAUTH_PROVIDER_UNKNOWN: 'OAUTH_PROVIDER_UNKNOWN',
  OAUTH_NOT_CONFIGURED: 'OAUTH_NOT_CONFIGURED',
  OAUTH_STATE_INVALID: 'OAUTH_STATE_INVALID',
  OAUTH_CODE_INVALID: 'OAUTH_CODE_INVALID',
  OAUTH_EMAIL_UNVERIFIED: 'OAUTH_EMAIL_UNVERIFIED',
  OAUTH_ACCOUNT_LINKED_ELSEWHERE: 'OAUTH_ACCOUNT_LINKED_ELSEWHERE',
  OAUTH_AUTHENTICATION_FAILED: 'OAUTH_AUTHENTICATION_FAILED',
  // feature:oauth-core:end

  // User Self-Service
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
  SAME_PASSWORD: 'SAME_PASSWORD',
  CANNOT_REVOKE_CURRENT_SESSION: 'CANNOT_REVOKE_CURRENT_SESSION',
  ADMIN_CANNOT_DEACTIVATE_SELF: 'ADMIN_CANNOT_DEACTIVATE_SELF',
  REAUTH_REQUIRED: 'REAUTH_REQUIRED',

  // Password Reset
  // Wrong code, no pending request, expired code and locked record all
  // answer PASSWORD_RESET_CODE_INVALID.
  PASSWORD_RESET_CODE_INVALID: 'PASSWORD_RESET_CODE_INVALID',
  USER_NOT_FOUND_FOR_RESET: 'USER_NOT_FOUND_FOR_RESET',

  // feature:oauth-core:start
  // Account Linking
  PROVIDER_ALREADY_LINKED: 'PROVIDER_ALREADY_LINKED',
  EMAIL_MISMATCH_ON_LINK: 'EMAIL_MISMATCH_ON_LINK',
  CANNOT_UNLINK_LAST_PROVIDER: 'CANNOT_UNLINK_LAST_PROVIDER',
  PROVIDER_NOT_LINKED: 'PROVIDER_NOT_LINKED',
  // feature:oauth-core:end

  // Permissions
  PERMISSION_ALREADY_EXISTS: 'PERMISSION_ALREADY_EXISTS',
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
  INVALID_PERMISSION_FORMAT: 'INVALID_PERMISSION_FORMAT',

  // Roles
  ROLE_NAME_TAKEN: 'ROLE_NAME_TAKEN',
  ROLE_PROTECTED: 'ROLE_PROTECTED',
  ROLE_HAS_USERS: 'ROLE_HAS_USERS',
  SYSTEM_ROLE_RENAME_FORBIDDEN: 'SYSTEM_ROLE_RENAME_FORBIDDEN',
  ADMIN_WILDCARD_REQUIRED: 'ADMIN_WILDCARD_REQUIRED',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

/**
 * Translation key prefix for error codes
 */
export const ERROR_CODE_TRANSLATION_PREFIX = 'errors.codes';

/**
 * Get the translation key for an error code
 * @param code - The error code from the API
 * @returns The translation key for the error message
 */
export function getErrorCodeTranslationKey(code: string): string {
  return `${ERROR_CODE_TRANSLATION_PREFIX}.${code}`;
}
