export const authSelectors = {
  main: 'auth-main',
  login: {
    title: 'login-title',
    form: 'login-form',
    email: 'login-email-input',
    password: 'login-password-input',
    submit: 'login-submit',
    register: 'signup-link',
    forgot: 'forgot-password-link',
  },
  register: {
    title: 'register-title',
    form: 'register-form',
    name: 'register-name-input',
    email: 'register-email-input',
    password: 'register-password-input',
    submit: 'register-submit',
    login: 'signin-link',
  },
  forgot: {
    title: 'forgot-password-title',
    form: 'forgot-password-form',
    email: 'forgot-password-email-input',
    submit: 'forgot-password-submit',
  },
  reset: {
    title: 'reset-password-title',
    form: 'reset-password-form',
    email: 'reset-password-email-input',
    code: 'reset-password-code-input',
    password: 'reset-password-password-input',
    confirmation: 'reset-password-confirmPassword-input',
    submit: 'reset-password-submit',
  },
  backToLogin: 'back-to-login-link',
  togglePassword: 'password-visibility-toggle',
  methodsLoading: 'auth-methods-loading',
  methodsEmpty: 'auth-methods-empty',
} as const;
