import fs from 'node:fs';
import path from 'node:path';
import { configureNginxDomains } from './config-transforms.js';
import {
  colors,
  log,
  toSnakeCase,
  readFile,
  writeFile,
  fileExists,
  backupFile,
  validateAppName,
  execFile,
  createSpinner,
  ROOT_DIR,
} from './cli-utils.js';

// ═══════════════════════════════════════════════════════════════
// Generate Configuration Files
// ═══════════════════════════════════════════════════════════════
export function generateEnvFile(config) {
  return `# Production Environment Configuration
# Generated by setup-production script

# ══════════════════════════════════════════
# Domain Configuration
# ══════════════════════════════════════════
NGINX_HOST=${config.domains.mainDomain}
MAIN_DOMAIN=${config.domains.mainDomain}
FRONTEND_DOMAIN=${config.domains.frontendDomain}
BACKEND_DOMAIN=${config.domains.backendDomain}

# ══════════════════════════════════════════
# Frontend Configuration
# ══════════════════════════════════════════
NEXT_PUBLIC_API_URL=https://${config.domains.backendDomain}

# ══════════════════════════════════════════
# Backend Configuration
# ══════════════════════════════════════════
NODE_ENV=production
CLIENT_URL=https://${config.domains.frontendDomain}
PORT=5000

# ══════════════════════════════════════════
# MongoDB Configuration
# ══════════════════════════════════════════
MONGO_DATABASE=${config.database.dbName}
MONGO_USERNAME=${config.database.username}
MONGO_PASSWORD=${config.database.password}
MONGO_URI=mongodb://${config.database.username}:${config.database.password}@mongodb:27017/${config.database.dbName}?authSource=admin

# ══════════════════════════════════════════
# SSL Configuration
# ══════════════════════════════════════════
SSL_TYPE=${config.ssl.sslType}
SSL_EMAIL=${config.ssl.email}

# ══════════════════════════════════════════
# Port Configuration
# ══════════════════════════════════════════
NGINX_HTTP_PORT=${config.ports.httpPort}
NGINX_HTTPS_PORT=${config.ports.httpsPort}

# ══════════════════════════════════════════
# Application Configuration
# ══════════════════════════════════════════
APP_NAME=${config.appName}

# ══════════════════════════════════════════
# Security
# ══════════════════════════════════════════
# JWT_SECRET=

# ══════════════════════════════════════════
# SMTP Configuration
# ══════════════════════════════════════════
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_SECURE=false
# SMTP_USER=your-email@gmail.com
# SMTP_PASS=your-app-password
# EMAIL_FROM=noreply@${config.domains.mainDomain}
`;
}

// ═══════════════════════════════════════════════════════════════
// Update Docker Compose
// ═══════════════════════════════════════════════════════════════
export function updateDockerCompose(config) {
  const filePath = path.join(ROOT_DIR, 'docker-compose.prod.yml');

  if (!fileExists(filePath)) {
    log.warn('docker-compose.prod.yml not found, skipping...');
    return;
  }

  // Backup original
  const backupPath = backupFile(filePath);
  if (backupPath) {
    log.info(`Backed up to ${path.basename(backupPath)}`);
  }

  let content = readFile(filePath);
  const appSlug = toSnakeCase(config.appName).replaceAll('_', '-');

  // Update container names
  content = content.replaceAll('authboiler-mongodb', `${appSlug}-mongodb`);
  content = content.replaceAll('authboiler-backend', `${appSlug}-backend`);
  content = content.replaceAll('authboiler-frontend', `${appSlug}-frontend`);
  content = content.replaceAll('authboiler-nginx', `${appSlug}-nginx`);
  content = content.replaceAll('authboiler-certbot', `${appSlug}-certbot`);

  // Update database name
  content = content.replaceAll(
    'MONGO_DATABASE:-authboiler',
    `MONGO_DATABASE:-${config.database.dbName}`,
  );
  content = content.replaceAll('/authboiler', `/${config.database.dbName}`);
  content = content.replaceAll(
    'MONGO_INITDB_DATABASE: authboiler',
    `MONGO_INITDB_DATABASE: ${config.database.dbName}`,
  );

  writeFile(filePath, content);
  log.success('docker-compose.prod.yml updated');
}

// ═══════════════════════════════════════════════════════════════
// Update Nginx Configuration
// ═══════════════════════════════════════════════════════════════
export function updateNginxConfig(config) {
  const configFiles = ['nginx/nginx.conf', 'nginx/production-nginx.conf'];
  for (const file of configFiles) {
    const filePath = path.join(ROOT_DIR, file);

    if (!fileExists(filePath)) {
      continue;
    }

    const backupPath = backupFile(filePath);
    if (backupPath) {
      log.info(`Backed up ${file}`);
    }

    const content = configureNginxDomains(readFile(filePath), config.domains);

    writeFile(filePath, content);
    log.success(`${file} updated`);
  }
}

// ═══════════════════════════════════════════════════════════════
// Generate SSL Certificates
// ═══════════════════════════════════════════════════════════════
export async function generateSSLCertificates(config) {
  log.step('Setting up SSL certificates...');

  const sslDir = path.join(ROOT_DIR, 'nginx', 'ssl');

  // Create SSL directory
  fs.mkdirSync(sslDir, { recursive: true });

  if (config.ssl.sslType === 'self-signed') {
    log.warn('Generating self-signed certificates (DEVELOPMENT ONLY)...');

    const spinner = createSpinner('Generating certificates...');
    spinner.start();

    if (!validateAppName(config.appName)) {
      spinner.stop(false);
      log.error('Application name contains characters that cannot be used in a certificate subject');
      return;
    }

    const keyout = path.join(sslDir, 'privkey.pem');
    const fullchain = path.join(sslDir, 'fullchain.pem');
    const result = execFile(
      'openssl',
      [
        'req',
        '-x509',
        '-nodes',
        '-days',
        '365',
        '-newkey',
        'rsa:2048',
        '-keyout',
        keyout,
        '-out',
        fullchain,
        '-subj',
        `/C=US/ST=State/L=City/O=${config.appName}/CN=${config.domains.mainDomain}`,
      ],
      { silent: true },
    );

    if (result.success) {
      fs.copyFileSync(fullchain, path.join(sslDir, 'chain.pem'));
      fs.chmodSync(fullchain, 0o644);
      fs.chmodSync(path.join(sslDir, 'chain.pem'), 0o644);
      fs.chmodSync(keyout, 0o600);
      spinner.stop(true);
      log.success('Self-signed certificates generated');
    } else {
      spinner.stop(false);
      log.error('Failed to generate certificates');
      log.error(result.error);
    }
  } else {
    log.info("Let's Encrypt certificates will be obtained when services start.");
    log.info('Make sure your domain DNS points to this server before starting.');
    log.info('');
    log.info('To obtain certificates, run:');
    console.log(`  ${colors.cyan}docker compose -f docker-compose.prod.yml up -d${colors.reset}`);
    console.log(
      `  ${colors.cyan}docker compose -f docker-compose.prod.yml run --rm certbot certonly --webroot --webroot-path /var/www/certbot --email ${config.ssl.email} --agree-tos --no-eff-email -d ${config.domains.mainDomain} -d ${config.domains.frontendDomain} -d ${config.domains.backendDomain}${colors.reset}`,
    );
  }
}
