export const AUTH_SCHEMA_VERSION = 1;

export const DEFAULT_AUTH_EPOCH = 1;

export const USER_AGENT_MAX_LENGTH = 512;
export const DEVICE_NAME_MAX_LENGTH = 64;
export const LINEARIZABLE_QUERY_MAX_TIME_MS = 5000;

export const WEB_ABSOLUTE_LIFETIME_MS = 7 * 24 * 60 * 60 * 1000;
export const WEB_IDLE_LIFETIME_MS = 30 * 60 * 1000;

export const NATIVE_ABSOLUTE_LIFETIME_MS = 30 * 24 * 60 * 60 * 1000;
export const NATIVE_IDLE_LIFETIME_MS = 7 * 24 * 60 * 60 * 1000;
export const NATIVE_ACCESS_LIFETIME_MS = 5 * 60 * 1000;
export const NATIVE_INITIAL_IDLE_MS = 5 * 60 * 1000;

export const ADMIN_ABSOLUTE_LIFETIME_MS = 8 * 60 * 60 * 1000;
export const ADMIN_IDLE_LIFETIME_MS = 15 * 60 * 1000;
export const SENSITIVE_ACTION_WINDOW_MS = 5 * 60 * 1000;

export const MAX_SESSIONS_PER_USER = 20;
export const MAX_ADMIN_SESSIONS_PER_USER = 5;

export const AUTHORIZATION_CODE_LIFETIME_MS = 60 * 1000;
export const PENDING_AUTH_LIFETIME_MS = 5 * 60 * 1000;

export const NATIVE_DPOP_PROOF_HEADER = 'DPoP';
export const NATIVE_DPOP_NONCE_HEADER = 'DPoP-Nonce';
export const NATIVE_DPOP_TOKEN_PATH = '/api/oauth/token';
export const NATIVE_DPOP_MAX_PROOF_BYTES = 8192;
export const NATIVE_DPOP_JTI_MAX_LENGTH = 128;
export const NATIVE_DPOP_IAT_TOLERANCE_MS = 60 * 1000;
export const NATIVE_DPOP_NONCE_BUCKET_MS = 60 * 1000;
export const NATIVE_DPOP_NONCE_DOMAIN = 'native-dpop-nonce:';
export const NATIVE_DPOP_PROOF_ID_TTL_MS = 150 * 1000;
export const NATIVE_DPOP_SECRET_MIN_LENGTH = 32;

export const NATIVE_DPOP_FAILURE_REASON = {
  PROOF_TOO_LARGE: 'NATIVE_DPOP_PROOF_TOO_LARGE',
  PROOF_MALFORMED: 'NATIVE_DPOP_PROOF_MALFORMED',
  PROOF_DUPLICATE_MEMBER: 'NATIVE_DPOP_PROOF_DUPLICATE_MEMBER',
  PROOF_HEADER_INVALID: 'NATIVE_DPOP_PROOF_HEADER_INVALID',
  PROOF_ALGORITHM_INVALID: 'NATIVE_DPOP_PROOF_ALGORITHM_INVALID',
  PROOF_JWK_INVALID: 'NATIVE_DPOP_PROOF_JWK_INVALID',
  PROOF_SIGNATURE_INVALID: 'NATIVE_DPOP_PROOF_SIGNATURE_INVALID',
  PROOF_METHOD_MISMATCH: 'NATIVE_DPOP_PROOF_METHOD_MISMATCH',
  PROOF_ADDRESS_MISMATCH: 'NATIVE_DPOP_PROOF_ADDRESS_MISMATCH',
  PROOF_IAT_INVALID: 'NATIVE_DPOP_PROOF_IAT_INVALID',
  PROOF_JTI_INVALID: 'NATIVE_DPOP_PROOF_JTI_INVALID',
  NONCE_REQUIRED: 'NATIVE_DPOP_NONCE_REQUIRED',
  NONCE_INVALID: 'NATIVE_DPOP_NONCE_INVALID',
  PROOF_ATH_INVALID: 'NATIVE_DPOP_PROOF_ATH_INVALID',
  PROOF_REPLAYED: 'NATIVE_DPOP_PROOF_REPLAYED',
  CONFIGURATION_INVALID: 'NATIVE_DPOP_CONFIGURATION_INVALID',
} as const;

export const SECURITY_EVENT_PURGE_MS = 90 * 24 * 60 * 60 * 1000;
